# This is a basic workflow to help you get started with Actions

name: Transform json to ttl

# Controls when the workflow will run
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install jsonschema requests pathlib2
      
      - name: Install Requirements
        run: |
          pip install -r .github/workflows/requirements.txt

      - name: Run Python script
        run: |
          python .github/workflows/scripts/main.py

      - name: Check for changes
        id: git-check
        run: |
          git status
          echo "changed=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT
  
      - name: Commit and push if changes
        if: steps.git-check.outputs.changed > 0
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto-generated TTL files $(date +'%Y-%m-%d')"
          git push
